# Generated by Django 5.2 on 2025-07-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_posted',
            new_name='posted_at',
        ),
    ]
