# Generated by Django 4.2.1 on 2025-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_date_posted_job_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('react', 'React'), ('remote', 'Remote')], default=('python', 'Python'), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
